class Ochered():
 def __init__(self):
  self.queue=[]
 def enqueue(self,item):
  self.queue.append(item)
 def dequeue(self):
     return self.queue.pop(0)
 def size(self):
     return len(self.queue)
Ochered1=Ochered()
Ochered1.enqueue(1)
Ochered1.enqueue(17)
Ochered1.enqueue(32)
Ochered1.enqueue(43)
Ochered1.enqueue(51)
Ochered1.dequeue()
print('очередь 1:',Ochered1.queue)
Ochered2=Ochered()
Ochered2.enqueue(4)
Ochered2.enqueue(11)
Ochered2.enqueue(18)
Ochered2.enqueue(22)
Ochered2.enqueue(25)
Ochered2.enqueue(43)
Ochered2.dequeue()
print('очередь 2:',Ochered2.queue)
Ochered3=Ochered()
Ochered3.enqueue(12)
Ochered3.enqueue(15)
Ochered3.enqueue(27)
Ochered3.enqueue(33)
Ochered3.dequeue()
Ochered3.dequeue()
print('очередь 3:',Ochered3.queue)
Ochered4=Ochered()
Ochered4.enqueue(7)
Ochered4.enqueue(10)
Ochered4.enqueue(28)
Ochered4.enqueue(52)
Ochered4.enqueue(75)
Ochered4.enqueue(86)
Ochered4.dequeue()
print('очередь 4:',Ochered4.queue)


